field: 7cadd0f5-3571-466a-b08d-5866c2ab6912 # Conference Program
fieldLayouts:
  ce8b9dee-7c64-465a-a473-33ec833ac256:
    tabs:
      -
        elements:
          -
            fieldUid: 498bd139-762d-494e-a10f-938061c9a610 # Day
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fb3426b-44db-4e5c-a0c4-c9af8f4c22a5
            warning: null
            width: 100
          -
            fieldUid: bb112ccb-9b0f-41f4-89bf-516a16f1f957 # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 722f0270-8b46-4e0a-8ffe-8662cc17347f
            warning: null
            width: 100
          -
            fieldUid: f738066a-9c97-42e0-af8a-e168bd6131db # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f178db3-082c-4bdb-86a5-bbba82a702b4
            warning: null
            width: 100
        name: Content
        uid: 1fc4200a-1780-42dd-9396-0f031ab1876b
fields:
  498bd139-762d-494e-a10f-938061c9a610: # Day
    columnSuffix: jhekwrke
    contentColumnType: text
    fieldGroup: null
    handle: day
    instructions: null
    name: Day
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bb112ccb-9b0f-41f4-89bf-516a16f1f957: # Date
    columnSuffix: yngcrubz
    contentColumnType: text
    fieldGroup: null
    handle: date
    instructions: null
    name: Date
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f738066a-9c97-42e0-af8a-e168bd6131db: # Text
    columnSuffix: jkzhihuz
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: conferenceProgram
name: 'Conference Program'
sortOrder: 1
