field: 1eb93128-c9cf-4c8b-b069-c4650db9130b # Alert link
fieldLayouts:
  8cad42a5-0589-4bd2-8b13-84e2452f3ad1:
    tabs:
      -
        elements:
          -
            fieldUid: e0a66bba-47d4-44ae-b699-f47a240cee6a # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6546fbd-2524-48d5-9035-da04960c7830 # Link text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6e28454-c877-49a8-99a5-ea996c9de804 # Related page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc3d7aa8-3629-47fb-b051-1d59796c54e4 # External link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  cc3d7aa8-3629-47fb-b051-1d59796c54e4: # External link
    columnSuffix: kyjxhips
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalLink
    instructions: 'If the alert is linking to an external website, add the URL here. NOTE: the related page field above will take precedence so make sure any entries are deleted there otherwise this link will not work.'
    name: 'External link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d6e28454-c877-49a8-99a5-ea996c9de804: # Related page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: relatedPage
    instructions: 'If the alert is linking to a page on the Health Translation Queensland website, add it here.'
    name: 'Related page'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Page link'
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  e0a66bba-47d4-44ae-b699-f47a240cee6a: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:366669c1-fe40-4067-b625-311d2125278b' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an icon (optional)'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:366669c1-fe40-4067-b625-311d2125278b' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f6546fbd-2524-48d5-9035-da04960c7830: # Link text
    columnSuffix: phrnxqbz
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: link
name: Link
sortOrder: 1
