field: 7fc2c416-28fb-4482-bda1-be409cc6abc1 # Partners
fieldLayouts:
  aec904a1-bdf8-40d8-bc48-cefb186b399c:
    tabs:
      -
        elements:
          -
            fieldUid: 69634455-80bf-41a0-8d99-74ef052d3271 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0ba477d-ed41-4298-9c4b-dd9cd8f8bd8e # Partner URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 462ed050-f7b1-4854-bcb3-f0f0bca35844 # Partner description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  462ed050-f7b1-4854-bcb3-f0f0bca35844: # Partner description
    columnSuffix: nqulwxbm
    contentColumnType: text
    fieldGroup: null
    handle: partnerDescription
    instructions: ''
    name: 'Partner description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  69634455-80bf-41a0-8d99-74ef052d3271: # Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: ''
    name: Logo
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:366669c1-fe40-4067-b625-311d2125278b' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add a logo'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:366669c1-fe40-4067-b625-311d2125278b' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f0ba477d-ed41-4298-9c4b-dd9cd8f8bd8e: # Partner URL
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: partnerUrl
    instructions: ''
    name: 'Partner URL'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: partners
name: Partners
sortOrder: 1
