field: e18a121f-68bb-4064-995e-186144e148f0 # Conference Program Title
fieldLayouts:
  c1e5946b-7bcc-4f4e-a841-22f8693006e2:
    tabs:
      -
        elements:
          -
            fieldUid: fa1f53ca-c019-43af-a59b-b1019c21de93 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92419b6e-47e6-49d3-abb4-179dd5a5b7a1
            warning: null
            width: 100
          -
            fieldUid: c8ee1d81-185c-4761-9c3c-35ec4686bbf5 # Download Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4843e2f4-866b-41ce-b2e2-9e46cbf28b5d
            warning: null
            width: 100
          -
            fieldUid: 81644cb1-aa71-4340-96be-355dd64c3090 # Download File
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 309ed948-bc8a-4056-841f-020358c573ea
            warning: null
            width: 100
        name: Content
        uid: 657f35ee-9d99-4d3a-be01-865b01a95f45
fields:
  81644cb1-aa71-4340-96be-355dd64c3090: # Download File
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: downloadFile
    instructions: null
    name: 'Download File'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:366669c1-fe40-4067-b625-311d2125278b' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:366669c1-fe40-4067-b625-311d2125278b' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c8ee1d81-185c-4761-9c3c-35ec4686bbf5: # Download Text
    columnSuffix: aradfiif
    contentColumnType: text
    fieldGroup: null
    handle: downloadText
    instructions: null
    name: 'Download Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fa1f53ca-c019-43af-a59b-b1019c21de93: # Heading
    columnSuffix: tbptjyqc
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: programTitle
name: 'Program Title'
sortOrder: 1
