fieldLayouts:
  53371963-92ca-464d-87af-c0aed14a539a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aae1b45f-2b28-4d22-a634-88e85c971845
            warning: null
            width: 100
          -
            fieldUid: 8555c534-f063-4475-bfc8-9e2baf8294b8 # Navigation matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6477cc2-b84a-4a45-abba-a7e759766bc4
            warning: null
            width: 100
          -
            fieldUid: 74859c8b-89db-4f54-8508-0aa8bc88f4fc # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6f51c7c-6bc3-4f6c-95e0-c589b0d629a9
            warning: null
            width: 100
          -
            fieldUid: 11cfc561-52bc-472f-901c-e106f0efea9a # Conference CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b0d3f79-fe57-44a1-88ca-d3fbbc555e50
            warning: null
            width: 100
          -
            fieldUid: e5b1dd21-c0a3-4b40-85eb-e291eeec85e2 # Two Column Image Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77b18114-d9a9-402f-a774-8f5deca494db
            warning: null
            width: 100
          -
            fieldUid: 2cd701b8-0709-4b5d-b1f8-cf074f2cb9b6 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7206949-321e-47de-ad50-f6cf2ba365fb
            warning: null
            width: 100
          -
            fieldUid: 7dab8e15-0975-49e0-92ce-ff701ba11a1d # Related Speakers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae430a3c-c8f8-4169-a064-53afbad098cb
            warning: null
            width: 100
          -
            fieldUid: ce3930e0-c644-4574-be77-785ee7c5d715 # Conference Countdown
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c5e2999-5626-4940-9bd7-8287b27cdc2f
            warning: null
            width: 100
          -
            fieldUid: e18a121f-68bb-4064-995e-186144e148f0 # Conference Program Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 044a95d6-0eba-4423-bbad-27e0a726632d
            warning: null
            width: 100
          -
            fieldUid: 7cadd0f5-3571-466a-b08d-5866c2ab6912 # Conference Program
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de16d69f-b0e7-4601-8fa6-e0d759224b57
            warning: null
            width: 100
          -
            fieldUid: fe1c2892-5220-4966-912a-4b036fbaf16e # CTA Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cac39665-b487-423a-8a7a-961ee4fde0f0
            warning: null
            width: 100
          -
            fieldUid: d8a753a5-fe72-4f3b-abeb-4d14b3874d85 # Sponsors Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1516ab6-3537-4e0e-9a8a-ee10781e4a60
            warning: null
            width: 100
          -
            fieldUid: 8d39f5fb-c63c-4a46-b9df-741619ccaa3d # Conference Sponsors
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b659598-f8ae-4e7b-93ea-62d084727bfa
            warning: null
            width: 100
          -
            fieldUid: 28098bdb-54c4-4865-910b-c2724e85a55e # FAQ Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f90b3c9-8c4b-4320-ac1b-192a02efb045
            warning: null
            width: 100
          -
            fieldUid: fe8184cc-ecc8-4f0c-9b55-533379a46965 # FAQ Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d52562c-c60c-431d-ad1b-c2407b897bbf
            warning: null
            width: 100
          -
            fieldUid: ad3e8376-41ac-4e32-9bfa-edc9ea34ee60 # Testimonial Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b00104b-259a-49a3-a9a7-fc08a34e8a56
            warning: null
            width: 100
          -
            fieldUid: 2eaab538-84d4-4454-9a79-814967319d20 # Testimonials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b5458d1-c242-4885-803b-e3a3ff9170bc
            warning: null
            width: 100
          -
            fieldUid: 823bd892-9bda-4ef9-bed3-6aa33cc14a7d # Conference Contact
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77394c50-1075-4ed8-a2ac-22a234094456
            warning: null
            width: 100
        name: Content
        uid: ceabd235-88f0-4a5c-a946-7fcf3246f9a0
handle: conference
hasTitleField: true
name: Conference
section: 4a18a6e6-7515-4a3e-a55e-11bfa193d188 # Conferences
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
