handle: themes
instructions: ''
maxNodes: ''
name: Themes
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
siteSettings:
  15197aeb-10d6-4ef2-a919-6bcc6108a1e8: null # Health Translation Queensland
sortOrder: 2
structure:
  maxLevels: null
  uid: ae09b509-1e56-448b-a6c6-32c2fc05b0ac
