columnSuffix: null
contentColumnType: string
fieldGroup: e7005114-b51a-43fa-b568-36cb5018a5ba # Vizy
handle: accordion
instructions: ''
name: Accordion
searchable: false
settings:
  contentTable: '{{%matrixcontent_accordion}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
