columnSuffix: null
contentColumnType: string
fieldGroup: d540c85c-a227-49d4-ab70-f39ba6d142ce # Home
handle: alertLink
instructions: ''
name: 'Alert link'
searchable: false
settings:
  contentTable: '{{%matrixcontent_alertlink}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
