columnSuffix: xhxnmlme
contentColumnType: string
fieldGroup: dea8b0e0-13fa-4259-8242-58d0a6c33979 # Conference
handle: conferenceCta
instructions: null
name: 'Conference CTA'
searchable: false
settings:
  contentTable: '{{%matrixcontent_conferencecta}}'
  maxBlocks: 1
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
