columnSuffix: xujxbrrk
contentColumnType: string(255)
fieldGroup: 8b7fd1bb-09d3-45b2-8a2f-6e3875ad480a # Common
handle: externalLink
instructions: ''
name: 'External link'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
    - tel
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
