columnSuffix: null
contentColumnType: string
fieldGroup: 8b7fd1bb-09d3-45b2-8a2f-6e3875ad480a # Common
handle: relatedContent
instructions: ''
name: 'Related content'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
