columnSuffix: null
contentColumnType: string
fieldGroup: 9b563bed-e98a-4151-909c-4d45e608fd39 # Globals
handle: socials
instructions: ''
name: Socials
searchable: false
settings:
  contentTable: '{{%matrixcontent_socials}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
