fieldLayouts:
  04047129-a3be-4706-8326-4972715777ed:
    tabs:
      -
        elements:
          -
            fieldUid: fe69e1d1-a32c-43b1-a787-d3813e3abf4d # Site logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7fc2c416-28fb-4482-bda1-be409cc6abc1 # Partners
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: CONTENT
        sortOrder: 1
handle: bottomFooter
name: 'Bottom footer'
sortOrder: 4
