fieldLayouts:
  97dc08ab-f4dd-4532-96c7-b9bd78e692c2:
    tabs:
      -
        elements:
          -
            fieldUid: 4e2c08fc-0231-4274-b3cb-4e217c1119ec # SEO title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b97ad6f6-eecd-44f5-908b-eadfddd3fdca # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 09257c28-9e7d-4f43-b8f7-597426429de9 # SEO Keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 078d14b6-6aa7-4bac-a8a8-b5edb105f8fb # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86ab1437-695b-4f84-9b37-479c67a77d1b # SEO image description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 1
handle: globalSeo
name: 'Global SEO'
sortOrder: 1
